#!/bin/bash
echo -e "\033[0;32mCompiling WASM"
pushd wasm
zig build
popd

echo -e "\033[0;32mCleaning dist..."
rm -r dist

echo -e "\033[0;32mCompiling typescript..."
./node_modules/.bin/tsc # Compile typescript

echo -e "\033[0;32mBundling..."
./node_modules/.bin/webpack # Bundle renderer.ts

# Copy html to dist
echo -e "\033[0;32mCopying source..."
cp src/index.html dist/
cp src/styles.css dist/

# Copy shaders
echo -e "\033[0;32mCopying shaders..."
mkdir -p "dist/renderer/shaders" "dist/renderer/shaders/source"
find "src/renderer/shaders/source" -name \*.glsl -exec cp {} "dist/renderer/shaders/source" \;

# Copy auxiliary apps
echo -e "\033[0;32mCopying auxiliary plugins"
mkdir -p dist/bin
cp bin/* ./dist/bin

# Source environment variables
echo -e "\033[32mLoading environment...\033[0m"
source .env
