#!/bin/bash
echo -e "\033[0;32mCleaning dist..."
rm -rf dist

echo -e "\033[0;32mCompiling WASM"
mkdir -p bin
pushd wasm
zig build
popd
cp ./wasm/zig-out/bin/peggiator.wasm ./bin/

echo -e "\033[0;32mCompiling typescript..."
/node_modules/.bin/tsc # Compile typescript